# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 768ffc340112969b3b469adb27b3f054583728d0893c034ea689af7a77dfe339d578cf23b2d1caf3a3ef6a55b749cfee26d9e1b577bd013b06fa3bb5bf9ccb6e

test:
  secret_key_base: c92dac40f68c71f606b0efee2af618164f9e310f00c42f6919d05da787e284fd17d25f7e9967d3e19941a3aeff746d37e05847f883a78f45fbb9909277ac7fd3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
